version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Production Dockerfile with 
    container_name: "jerry_project_production"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python ./manage.py runserver  "
    ports:
      - "8080:80"  # Expose Apache on port 80
    volumes:
      - "/var/www/Jerry-Project:/app"  # Path on VPS host
    env_file:
      - .env  # Separate production environment file
    depends_on:
      - db
      - redis
    networks:
      - my_network

  daphne:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: "daphne"
    command: "daphne -p 8001 jerry_project.asgi:application"
    ports:
      - "8001:8001"
    volumes:
      - "/var/www/Jerry-Project:/app"  # Updated for Windows path
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - my_network

  

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6370:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
