services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: "jerry_project"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"


    
    ports:
      - "8000:8000"
    volumes:
      - "D:/jerry project/Jerry-Project:/app"  # Updated for Windows path
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - my_network

  daphne:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: "daphne"
    command: "daphne -p 8001 jerry_project.asgi:application"
    ports:
      - "8001:8001"
    volumes:
      - "D:/jerry project/Jerry-Project:/app"  # Updated for Windows path
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - my_network

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Ensure this path exists on host
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - my_network

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6370:6379"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:


  