version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod  # Production Dockerfile
    container_name: "jerry_project_production"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && apache2ctl -D FOREGROUND"  # Start Apache instead of runserver
    ports:
      - "80:80"   # Map Apache's port 80 to host port 8081 (to avoid conflict with your existing website)
      - "443:443"  # Expose Apache on port 443 for HTTPS
    volumes:
      - "/var/www/Jerry-Project:/app"  # Path on VPS host
      - /etc/letsencrypt/live/shareyourclips.online/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/shareyourclips.online/privkey.pem:/etc/ssl/private/privkey.pem  # Mount SSL certificates
    env_file:
      - .env  # Separate production environment file
    depends_on:
      - db
      - redis
    networks:
      - my_network
    restart: always

  daphne:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: "daphne"
    command: "daphne -p 8001 jerry_project.asgi:application"
    ports:
      - "8001:8001"
    volumes:
      - "/var/www/Jerry-Project:/app"  # Updated for Windows path
      - /etc/letsencrypt/live/shareyourclips.online/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/shareyourclips.online/privkey.pem:/etc/ssl/private/privkey.pem  # Mount SSL certificates
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - my_network
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Ensure persistent database storage
    env_file:
      - .env
    ports:
      - "5433:5432"
    networks:
      - my_network

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6370:6379"
    networks:
      - my_network
    restart: always

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:  # Persistent volume for database data
