# Generated by Django 5.1.1 on 2024-09-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_postreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
