# Generated by Django 5.1.1 on 2024-09-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_mainnotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainnotification',
            options={'verbose_name': 'Notification'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Chat Message Notification'},
        ),
        migrations.AlterField(
            model_name='mainnotification',
            name='link',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
