# Generated by Django 5.1.1 on 2024-09-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_mainnotification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnotification',
            name='link',
            field=models.CharField(blank=True, default='#', max_length=100, null=True, verbose_name='Redirect Link'),
        ),
    ]
