# Generated by Django 5.1.1 on 2024-09-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_alter_mainnotification_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainnotification',
            options={'verbose_name': 'Send Notification To User'},
        ),
        migrations.AlterField(
            model_name='mainnotification',
            name='link',
            field=models.CharField(blank=True, default='#', help_text='Example: https://www.bmy.fan/page/policy/ - The user will be redirected to the specified page upon clicking.', max_length=100, null=True, verbose_name='Redirect Link'),
        ),
    ]
