# Generated by Django 5.1.1 on 2024-09-15 15:31

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_menu', models.BooleanField(default=False)),
                ('page_url', models.CharField(max_length=100)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
            ],
        ),
    ]
