# Generated by Django 5.1.1 on 2024-09-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='page_url',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
