# Generated by Django 5.1.1 on 2024-09-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_pages_page_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='deleted',
            field=models.IntegerField(default=0),
        ),
    ]
