# Generated by Django 5.1.1 on 2024-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pages_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
