# Generated by Django 5.1.1 on 2024-09-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pages_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
    ]
