# Generated by Django 5.1.1 on 2024-09-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pages_show_in_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Create New Page'},
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_name',
            field=models.CharField(help_text='The name to show for user to click', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_url',
            field=models.CharField(help_text="Example:-terms_and_condtion.... and make sure to user undercorse '_' not spaces", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='show_in_footer',
            field=models.BooleanField(default=False, help_text='Select to display this page in the footer.'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='show_in_menu',
            field=models.BooleanField(default=False, help_text='Select to display this page in the menu bar.'),
        ),
    ]
