# Generated by Django 5.1.1 on 2024-10-05 16:48

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_pages_options_alter_pages_page_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_menu', models.BooleanField(default=False, help_text='Select to display this page in the menu bar.')),
                ('show_in_footer', models.BooleanField(default=False, help_text='Select to display this page in the footer.')),
                ('page_url', models.CharField(help_text="Example:-terms_and_condtion.... and make sure to user undercorse '_' not spaces", max_length=100, unique=True)),
                ('page_name', models.CharField(help_text='The name to show for user to click', max_length=100, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': "Fan's Page",
            },
        ),
        migrations.CreateModel(
            name='SimultaneouslyPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_in_menu', models.BooleanField(default=False, help_text='Select to display this page in the menu bar.')),
                ('show_in_footer', models.BooleanField(default=False, help_text='Select to display this page in the footer.')),
                ('page_url', models.CharField(help_text="Example:-terms_and_condtion.... and make sure to user undercorse '_' not spaces", max_length=100, unique=True)),
                ('page_name', models.CharField(help_text='The name to show for user to click', max_length=100, unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': "Simultaneously_Pages (Pages for both creator's and fan's)",
                'verbose_name_plural': "Simultaneously_Pages (Pages for both creator's and fan's)",
            },
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': "Creator's Page"},
        ),
    ]
