# Generated by Django 5.1.1 on 2024-11-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_fanpages_simultaneouslypages_alter_pages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanpages',
            name='deleted',
            field=models.IntegerField(default=0, help_text="This is for soft delete '1' for delete and '0' for not to delete  "),
        ),
        migrations.AlterField(
            model_name='fanpages',
            name='page_name',
            field=models.CharField(help_text='exmaple:- terms and condition ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='fanpages',
            name='page_url',
            field=models.CharField(help_text="Example:-terms_and_condtion  for this url https://www.bmy.fan/pages/terms_and_condition and make suer to underscore '_' or dess '-' ", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='deleted',
            field=models.IntegerField(default=0, help_text="This is for soft delete '1' for delete and '0' for not to delete  "),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_name',
            field=models.CharField(help_text='exmaple:- terms and condition ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_url',
            field=models.CharField(help_text="Example:-terms_and_condtion  for this url https://www.bmy.fan/pages/terms_and_condition and make suer to underscore '_' or dess '-' ", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='simultaneouslypages',
            name='deleted',
            field=models.IntegerField(default=0, help_text="This is for soft delete '1' for delete and '0' for not to delete  "),
        ),
        migrations.AlterField(
            model_name='simultaneouslypages',
            name='page_name',
            field=models.CharField(help_text='exmaple:- terms and condition ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='simultaneouslypages',
            name='page_url',
            field=models.CharField(help_text="Example:-terms_and_condtion  for this url https://www.bmy.fan/pages/terms_and_condition and make suer to underscore '_' or dess '-' ", max_length=100, unique=True),
        ),
    ]
