# Generated by Django 4.2.3 on 2024-08-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_deleted_message_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='is_read_by_user1',
        ),
        migrations.AddField(
            model_name='message',
            name='is_read_by_user2',
            field=models.BooleanField(default=False),
        ),
    ]
