# Generated by Django 4.2.3 on 2024-08-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_is_read_message_is_read_by_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_message_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
