# Generated by Django 4.2.3 on 2024-08-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_uploadedimage_message_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
    ]
