# Generated by Django 5.1.1 on 2024-09-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'verbose_name': 'Uploaded Image', 'verbose_name_plural': 'Uploaded Images'},
        ),
    ]
