# Generated by Django 5.1.1 on 2024-09-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_uploadedimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'Conversation Thread Between User'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Conversation Messages (Here you will see all the messages of all conversations)', 'verbose_name_plural': 'Conversation Messages (Here you will see all the messages of all conversations)'},
        ),
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'verbose_name': 'Uploaded Image ', 'verbose_name_plural': 'Uploaded Images'},
        ),
    ]
