# Generated by Django 4.2.3 on 2024-08-16 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_alter_creatorapproval_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorapproval',
            name='age',
            field=models.BooleanField(default=False, null=True, verbose_name='Age Above 21'),
        ),
        migrations.AlterField(
            model_name='creatorapproval',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='creatorapproval',
            name='terms_of_service',
            field=models.BooleanField(default=False, null=True, verbose_name='Terms and Conditions Accepted'),
        ),
    ]
