# Generated by Django 5.1.1 on 2024-10-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=100)),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Billing', 'Billing'), ('Account', 'Account'), ('Creator Approval', 'Creator Approval'), ('Creator Onboarding', 'Creator Onboarding'), ('Purchasing', 'Purchasing'), ('Refund', 'Refund'), ('Video Approval', 'Video Approval'), ('Policy Violations', 'Policy Violations'), ('General', 'General')], default='General', max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('support_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support_ticket.support_ticket')),
            ],
        ),
    ]
