# Generated by Django 5.1.1 on 2024-10-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0002_support_ticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='uploaded_at',
        ),
    ]
