# Generated by Django 5.1.1 on 2024-10-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0003_remove_attachment_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support_ticket',
            name='subject',
        ),
    ]
