# Generated by Django 5.1.1 on 2024-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0004_remove_support_ticket_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_ticket',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
