# Generated by Django 5.1.1 on 2024-10-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0005_support_ticket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('InProgess', 'InProgess'), ('Closed', 'Closed')], default='Open'),
        ),
    ]
