# Generated by Django 5.1.1 on 2024-11-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_ticket', '0006_support_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('InProgress', 'InProgress'), ('Closed', 'Closed')], default='Open'),
        ),
    ]
