# Generated by Django 5.0.7 on 2024-07-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='default_profile_image.jpg', upload_to='profile_pictures/'),
        ),
    ]
