# Generated by Django 5.0.7 on 2024-07-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default_profile_image.png', upload_to='profile_pictures/'),
        ),
    ]
