# Generated by Django 4.2.3 on 2024-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Welcome to my profile!\nI’m excited to connect with you and share my journey.\nFeel free to explore my posts and reach out if you’d like to collaborate!', max_length=1000),
        ),
    ]
