# Generated by Django 5.1.1 on 2024-11-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Welcome to my profile!\nI’m excited to connect with you and share my journey.\nFeel free to explore my posts and reach out if you’d like to collaborate!', max_length=10000),
        ),
    ]
