# Generated by Django 5.1.1 on 2024-09-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostReview',
        ),
    ]
