# Generated by Django 5.1.1 on 2024-09-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_delete_postreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video Approval', 'verbose_name_plural': 'Video Approvals'},
        ),
    ]
